-- Your SQL goes here
CREATE TABLE msg (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    sender VARCHAR(255) NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    sent_at TIMESTAMP NOT NULL DEFAULT NOW()
);
