name: Cacher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v3
      - run: rustup toolchain isntall stable --profile minimal
      - name: cacher
      - uses: Swatinem/rust-cache@v2
      
